### ISSUE TITLE
Fix ci

### ISSUE THREAD

**Issue by kehh** [wamuseum/providence#167]
https://travis-ci.org/wamuseum/providence
WA Museum fork: [![Build Status](https://secure.travis-ci.org/wamuseum/providence.png?branch=develop)](http://travis-ci.org/wamuseum/providence)

https://github.com/wamuseum/providence/compare/develop...kehh:profileUpdate20150507?expand=1

**Comment by leftclickben** [comment]
I pushed the changes to your branch so you can put up a PR:

https://travis-ci.org/kehh/providence

Kehan fork, branch=profileUpdate20150507: [![Build Status](https://secure.travis-ci.org/kehh/providence.png?branch=profileUpdate20150507)](http://travis-ci.org/wamuseum/kehh)

**Comment by leftclickben** [comment]
Sorry I know we talked about pushing to a branch on my fork, but I guess it doesn't matter.  Actually I thought there was a PR already for your branch.

The issue was simply that one of the list items ("access" list, "internal_only" item) was missing a `value` attribute, so it was falling back to the non-numeric `idno` value, which is an error for a numeric field.

This is the error message, which was being nicely swallowed by some code in one of the `BaseModel` classes:

```
[opn_error_number:Error:private] => 1100
[ops_error_description:Error:private] => 'internal_only' for access is not numeric
[ops_error_context:Error:private] => BaseModel->set()
```
